[package]
# Really Cool Memory Allocator
name = "rcmalloc" 
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "*"

[lib]
name = "rcmalloc"
path = "src/lib.rs"

[[bin]]
name = "alloc-test"
path = "src/main.rs"

[features]
debug_alloc = []
